name: build-attested-image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    env:
      REGISTRY: docker.io
      IMAGE_NAME:  nitritesh/gitactions

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: nitritesh
          password:  ${{ secrets.DKR_TKN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          provenance: mode=max
          tags: ${{ steps.meta.outputs.tags }}
          
          
      # - name: Build and push image
      #   id: push
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     push: true
      #     provenance: mode=max
      #     tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          
      # - name: Attest
      #   uses: actions/attest-build-provenance@v1
      #   id: attest
      #   with:
      #     subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     push-to-registry: true
